services:
  - type: web
    name: adoption-api
    runtime: node
    buildCommand: "npm install && mkdir -p uploads"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: "mongodb+srv://abhishekeb2003_db_animal:Animal@cluster0.cmhsn9e.mongodb.net/animaladoption"
      - key: JWT_SECRET
        value: "your-super-secret-jwt-key-change-this-in-production"
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: CLOUDINARY_CLOUD_NAME
        value: "SET_YOUR_CLOUDINARY_CLOUD_NAME"
      - key: CLOUDINARY_API_KEY
        value: "SET_YOUR_CLOUDINARY_API_KEY"
      - key: CLOUDINARY_API_SECRET
        value: "SET_YOUR_CLOUDINARY_API_SECRET"
    plan: free
